version: "3.5"

networks:
  odp-net:
    name: odp-net

services:
  odp-identity:
    container_name: odp-identity
    build:
      context: ..
      dockerfile: deploy/core-services/odp-identity/Dockerfile-${SERVER_ENV}
      args:
        - CA_CERT_URL=${ODP_ADMIN_URL}/ca.crt
    networks:
      - odp-net
    ports:
      - "9024:9024"
    environment:
      - FLASK_ENV=${SERVER_ENV}
      - FLASK_SECRET_KEY=${IDENTITY_FLASK_KEY}
      - DATABASE_URL=postgresql://odp_user:${ACCOUNTS_DB_PASSWORD}@${ACCOUNTS_DB_HOST}:5432/odp_accounts
      - MAIL_SERVER
      - ADMIN_INSTITUTION=saeon
      - HYDRA_ADMIN_URL=${ODP_ADMIN_URL}/hydra
      - HYDRA_LOGIN_EXPIRY=2592000
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips=*
    restart: always

  odp-admin:
    container_name: odp-admin
    build:
      context: ..
      dockerfile: deploy/core-services/odp-admin/Dockerfile-${SERVER_ENV}
      args:
        - CA_CERT_URL=${ODP_ADMIN_URL}/ca.crt
    networks:
      - odp-net
    ports:
      - "9025:9025"
    environment:
      - FLASK_ENV=${SERVER_ENV}
      - FLASK_SECRET_KEY=${ADMIN_FLASK_KEY}
      - FLASK_ADMIN_SWATCH=flatly
      - DATABASE_URL=postgresql://odp_user:${ACCOUNTS_DB_PASSWORD}@${ACCOUNTS_DB_HOST}:5432/odp_accounts
      - HYDRA_PUBLIC_URL=${ODP_PUBLIC_URL}/auth
      - HYDRA_ADMIN_URL=${ODP_ADMIN_URL}/hydra
      - OAUTH2_CLIENT_ID=odp-admin
      - OAUTH2_CLIENT_SECRET=${ADMIN_OAUTH2_SECRET}
      - OAUTH2_SCOPES=openid ODP.Admin
      - ADMIN_INSTITUTION=saeon
      - ADMIN_ROLE=admin
      - ADMIN_SCOPE=ODP.Admin
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips=*
    restart: always

  odp-admin-api:
    container_name: odp-admin-api
    build:
      context: ..
      dockerfile: deploy/core-services/odp-admin-api/Dockerfile-${SERVER_ENV}
      args:
        - CA_CERT_URL=${ODP_ADMIN_URL}/ca.crt
    networks:
      - odp-net
    ports:
      - "9999:9999"
    environment:
      - SERVER_ENV
      - PATH_PREFIX=/api
      - ADMIN_API_URL=${ODP_ADMIN_URL}/api
      - DATABASE_URL=postgresql://odp_user:${ACCOUNTS_DB_PASSWORD}@${ACCOUNTS_DB_HOST}:5432/odp_accounts
      - HYDRA_ADMIN_URL=${ODP_ADMIN_URL}/hydra
      - ADMIN_INSTITUTION=saeon
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    restart: always

  hydra:
    container_name: hydra
    image: ${HYDRA_IMAGE}
    networks:
      - odp-net
    ports:
      - "9000:4444"
      - "9001:4445"
    environment:
      - URLS_SELF_ISSUER=${ODP_PUBLIC_URL}/auth
      - SECRETS_SYSTEM=${HYDRA_SYSTEM_SECRET}
      - DSN=postgres://hydra_user:${HYDRA_DB_PASSWORD}@${HYDRA_DB_HOST}:5432/hydra_db?sslmode=disable
      - URLS_LOGIN=${ODP_PUBLIC_URL}/id/hydra/login
      - URLS_CONSENT=${ODP_PUBLIC_URL}/id/hydra/consent
      - URLS_LOGOUT=${ODP_PUBLIC_URL}/id/hydra/logout
      # TODO remove; the following makes access token lifetime 1 week (the default is 1 hour),
      # as a workaround until such time as we've implemented token refresh on the client side
      - TTL_ACCESS_TOKEN=168h
    restart: always
