version: "3.5"

networks:
  odp-net:
    name: odp-net
  ckan-net:
    name: ckan-net
  elastic-net:
    name: elastic-net

volumes:
  elastic-data:
    name: elastic-data

services:
  odp-identity:
    container_name: odp-identity
    build:
      context: ..
      dockerfile: deploy/odp-identity/Dockerfile
      args:
        - CA_CERT_URL=${ODP_ADMIN_URL}/ca.crt
    networks:
      - odp-net
    ports:
      - "9024:9024"
    environment:
      - ODP_ENV
      - FLASK_ENV=${ODP_ENV}
      - ODP_IDENTITY_FLASK_KEY
      - ODP_DB_HOST
      - ODP_DB_NAME
      - ODP_DB_USER
      - ODP_DB_PASS
      - ODP_MAIL_HOST
      - ODP_ADMIN_INSTITUTION=saeon
      - ODP_ADMIN_ROLE=admin
      - ODP_ADMIN_SCOPE=ODP.Admin
      - ODP_IDENTITY_LOGIN_EXPIRY=2592000
      - HYDRA_ADMIN_URL=${ODP_ADMIN_URL}/hydra
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips=*
    restart: always

  odp-admin:
    container_name: odp-admin
    build:
      context: ..
      dockerfile: deploy/odp-admin/Dockerfile
      args:
        - CA_CERT_URL=${ODP_ADMIN_URL}/ca.crt
    networks:
      - odp-net
    ports:
      - "9025:9025"
    environment:
      - ODP_ENV
      - FLASK_ENV=${ODP_ENV}
      - ODP_ADMIN_UI_FLASK_KEY
      - ODP_ADMIN_UI_THEME=flatly
      - ODP_DB_HOST
      - ODP_DB_NAME
      - ODP_DB_USER
      - ODP_DB_PASS
      - HYDRA_PUBLIC_URL=${ODP_PUBLIC_URL}/auth
      - HYDRA_ADMIN_URL=${ODP_ADMIN_URL}/hydra
      - ODP_ADMIN_UI_CLIENT_ID
      - ODP_ADMIN_UI_CLIENT_SECRET
      - ODP_ADMIN_UI_SCOPE=["openid","ODP.Admin"]
      - ODP_ADMIN_INSTITUTION=saeon
      - ODP_ADMIN_ROLE=admin
      - ODP_ADMIN_SCOPE=ODP.Admin
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips=*
    restart: always

  odp-admin-api:
    container_name: odp-admin-api
    build:
      context: ..
      dockerfile: deploy/odp-admin-api/Dockerfile
      args:
        - CA_CERT_URL=${ODP_ADMIN_URL}/ca.crt
    networks:
      - odp-net
    ports:
      - "9999:9999"
    environment:
      - ODP_ENV
      - ODP_API_PATH_PREFIX=/api
      - ODP_API_ADMIN_API_URL=http://odp-admin-api:9999
      - ODP_DB_HOST
      - ODP_DB_NAME
      - ODP_DB_USER
      - ODP_DB_PASS
      - HYDRA_ADMIN_URL=${ODP_ADMIN_URL}/hydra
      - ODP_ADMIN_INSTITUTION=saeon
      - ODP_ADMIN_ROLE=admin
      - ODP_ADMIN_SCOPE=ODP.Admin
      - CKAN_URL=http://ckan-metadata:5000
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    restart: always

  odp-public-api:
    container_name: odp-public-api
    build:
      context: ..
      dockerfile: deploy/odp-public-api/Dockerfile
      args:
        - CA_CERT_URL=${ODP_ADMIN_URL}/ca.crt
    networks:
      - odp-net
      - ckan-net
      - elastic-net
    ports:
      - "8888:8888"
    environment:
      - ODP_ENV
      - ODP_API_PATH_PREFIX=/api
      - ODP_API_ALLOW_ORIGINS
      - ODP_API_ADMIN_API_URL=http://odp-admin-api:9999
      - ODP_DB_HOST
      - ODP_DB_NAME
      - ODP_DB_USER
      - ODP_DB_PASS
      - ODP_ADMIN_INSTITUTION=saeon
      - ODP_ADMIN_ROLE=admin
      - ODP_ADMIN_SCOPE=ODP.Admin
      - HYDRA_ADMIN_URL=${ODP_ADMIN_URL}/hydra
      - CKAN_URL=http://ckan-metadata:5000
      - ELASTIC_URL=http://elasticsearch:9200
      - ELASTIC_INDICES
      - CATALOGUE_METADATA_LANDING_PAGE_BASE_URL
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    restart: always

  odp-publisher:
    container_name: odp-publisher
    build:
      context: ..
      dockerfile: deploy/odp-publisher/Dockerfile
      args:
        - ODP_PUBLISH_JOB_INTERVAL
    environment:
      - ODP_ENV
      - ODP_LOG_LEVEL
      - ODP_PUBLISH_HARVEST_CHECK_INTERVAL
      - ODP_PUBLISH_BATCH_SIZE
      - ODP_PUBLISH_MAX_RETRIES
      - ODP_DB_HOST
      - ODP_DB_NAME
      - ODP_DB_USER
      - ODP_DB_PASS
      - CKAN_URL
      - CKAN_DB_HOST
      - CKAN_DB_NAME
      - CKAN_DB_USER
      - CKAN_DB_PASS
      - DATACITE_API_URL
      - DATACITE_USERNAME
      - DATACITE_PASSWORD
      - DATACITE_DOI_PREFIX
      - DATACITE_DOI_LANDING_PAGE_BASE_URL=${ODP_PUBLIC_URL}/api/catalogue/go
    restart: always

  hydra:
    container_name: hydra
    image: ${HYDRA_IMAGE}
    networks:
      - odp-net
    ports:
      - "9000:4444"
      - "9001:4445"
    environment:
      - URLS_SELF_ISSUER=${ODP_PUBLIC_URL}/auth
      - SECRETS_SYSTEM=${HYDRA_SYSTEM_SECRET}
      - DSN=postgres://${HYDRA_DB_USER}:${HYDRA_DB_PASS}@${HYDRA_DB_HOST}:5432/${HYDRA_DB_NAME}?sslmode=disable
      - URLS_LOGIN=${ODP_PUBLIC_URL}/id/hydra/login
      - URLS_CONSENT=${ODP_PUBLIC_URL}/id/hydra/consent
      - URLS_LOGOUT=${ODP_PUBLIC_URL}/id/hydra/logout
      # TODO remove; the following makes access token lifetime 1 week (the default is 1 hour),
      # as a workaround until such time as we've implemented token refresh on the client side
      - TTL_ACCESS_TOKEN=168h
    restart: always

  ckan-metadata:
    container_name: ckan-metadata
    build:
      context: ckan-metadata
      args:
        - SERVER_ENV=${ODP_ENV}
        - CA_CERT_URL=${ODP_ADMIN_URL}/ca.crt
        - CKAN_URL
        - CKAN_DB_URL=postgresql://${CKAN_DB_USER}:${CKAN_DB_PASS}@${CKAN_DB_HOST}/${CKAN_DB_NAME}
        - DOI_PREFIX=${DATACITE_DOI_PREFIX}
        - ODP_INTROSPECTION_URL=${ODP_ADMIN_URL}/api/auth/introspect
        - HYDRA_PUBLIC_URL=${ODP_PUBLIC_URL}/auth
        - OAUTH2_CLIENT_ID=${CKAN_CLIENT_ID}
        - OAUTH2_CLIENT_SECRET=${CKAN_CLIENT_SECRET}
        - OAUTH2_SCOPE=ODP.Metadata
        - IDENTITY_SERVICE_URL=${ODP_PUBLIC_URL}/id
        - ELASTIC_AGENT_URL=http://es-agent:9210
        - SOLR_URL=http://solr:8983/solr
        - REDIS_URL=http://redis:6379/0
        - RABBITMQ_HOST=rabbitmq
        - CKAN_ADMIN_ORG=saeon
        - CKAN_ADMIN_ROLE=admin
        - CKAN_CURATOR_ROLE=curator
        - CKAN_CONTRIBUTOR_ROLE=contributor
    networks:
      - ckan-net
      - elastic-net
    ports:
      - "5000:5000"
    environment:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    depends_on:
      - solr
      - redis
      - rabbitmq
    restart: always

  pycsw:
    container_name: pycsw
    build:
      context: pycsw
      args:
        - ELASTIC_AGENT_SEARCH_URL=http://es-agent:9210/search
    networks:
      - elastic-net
    ports:
      - "8000:8000"
    depends_on:
      - es-agent
    restart: always

  es-agent:
    container_name: es-agent
    build:
      context: es-agent
    networks:
      - elastic-net
    ports:
      - "9210:9210"
    environment:
      - ELASTIC_AGENT_HOST=localhost
      - ELASTIC_AGENT_PORT=9210
      - ELASTIC_SEARCH_HOST=elasticsearch
      - ELASTIC_SEARCH_PORT=9200
    depends_on:
      - elasticsearch
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    networks:
      - elastic-net
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data/
    restart: always

  solr:
    container_name: solr
    build:
      context: solr
    networks:
      - ckan-net
    restart: always

  redis:
    container_name: redis
    image: redis:5
    networks:
      - ckan-net
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    networks:
      - ckan-net
    restart: always
