version: "3.5"

networks:
  odp-net:
    name: odp-net
    external: true
  ckan-net:
    name: ckan-net

volumes:
  hydra-data:
    name: hydra-data
    external: true

services:
  hydra:
    container_name: hydra
    image: ${HYDRA_IMAGE}
    command: serve all --dangerous-force-http
    networks:
      - odp-net
    ports:
      - "9000:4444"
      - "9001:4445"
    environment:
      - URLS_SELF_ISSUER=http://localhost:9000
      - URLS_LOGIN=http://localhost:9024/hydra/login
      - URLS_CONSENT=http://localhost:9024/hydra/consent
      - URLS_LOGOUT=http://localhost:9024/hydra/logout
      - SECRETS_SYSTEM=${HYDRA_SYSTEM_SECRET}
      - DSN=postgres://hydra_user:${HYDRA_DB_PASS}@hydra-db:5432/hydra_db?sslmode=disable
      - TTL_ACCESS_TOKEN=168h
      - LOG_LEAK_SENSITIVE_VALUES=true
    depends_on:
      - hydra-db
    restart: always

  hydra-db:
    container_name: hydra-db
    image: postgres:11
    networks:
      - odp-net
    volumes:
      - hydra-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=hydra_db
      - POSTGRES_USER=hydra_user
      - POSTGRES_PASSWORD=${HYDRA_DB_PASS}
    restart: always

  redis:
    container_name: redis
    image: redis:5
    networks:
      - ckan-net
    ports:
      - "6379:6379"
    restart: always
