version: "3.5"

volumes:
  odp-data:
    name: DEV-odp-data
  hydra-data:
    name: DEV-hydra-data

services:
  odp-db:
    container_name: DEV-odp-db
    image: postgres:14
    ports:
      - "1337:5432"
    volumes:
      - odp-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${ODP_DB_NAME}
      - POSTGRES_USER=${ODP_DB_USER}
      - POSTGRES_PASSWORD=${ODP_DB_PASS}
    restart: always

  hydra:
    container_name: DEV-hydra
    image: ${HYDRA_IMAGE}
    command: serve all --dangerous-force-http
    ports:
      - "9000:4444"
      - "9001:4445"
    environment:
      - DSN=postgres://hydra_user:pass@hydra-db:5432/hydra_db?sslmode=disable
      - SECRETS_SYSTEM=8a9c0d27e04e7ba1
      - URLS_SELF_ISSUER=http://localhost:9000
      - URLS_LOGIN=${ODP_IDENTITY_URL}/hydra/login
      - URLS_CONSENT=${ODP_IDENTITY_URL}/hydra/consent
      - URLS_LOGOUT=${ODP_IDENTITY_URL}/hydra/logout
      - LOG_LEAK_SENSITIVE_VALUES=true
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SERVE_PUBLIC_CORS_ALLOWED_HEADERS=Authorization,Content-Type,X-Requested-With
      # uncomment for short-lived access tokens
      #- TTL_ACCESS_TOKEN=1m
    depends_on:
      - hydra-db
      - hydra-migrate
    restart: always

  hydra-db:
    container_name: DEV-hydra-db
    image: postgres:14
    volumes:
      - hydra-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=hydra_db
      - POSTGRES_USER=hydra_user
      - POSTGRES_PASSWORD=pass
    restart: always

  hydra-migrate:
    container_name: DEV-hydra-migrate
    image: ${HYDRA_IMAGE}
    command: migrate sql -e --yes
    environment:
      - DSN=postgres://hydra_user:pass@hydra-db:5432/hydra_db?sslmode=disable
    depends_on:
      - hydra-db
    restart: on-failure

  redis:
    container_name: DEV-redis
    image: redis:6
    ports:
      - "1379:6379"
    restart: always
