version: "3.5"

networks:
  ckan-net:
    name: ckan-net

services:
  solr:
    container_name: solr
    build:
      context: ../deploy/solr
    networks:
      - ckan-net
    ports:
      - "8983:8983"
    restart: always

  redis:
    container_name: redis
    image: redis:5
    networks:
      - ckan-net
    ports:
      - "6379:6379"
    restart: always
